name: Release Build Test

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

jobs:
    build:
        runs-on: windows-2022

        strategy:
            matrix:
                configuration: [ Release ]
                platform: [ x64 ]
            fail-fast: false

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Set UTF-8 Code Page
              run: |
                  chcp 65001
                  [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
                  [Console]::InputEncoding = [System.Text.Encoding]::UTF8

            - name: Build Solution
              run: |
                  chcp 65001
                  msbuild GTL.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v143 /verbosity:minimal

            - name: Upload Build Artifacts
              if: success()
              uses: actions/upload-artifact@v4
              with:
                  name: game-jam-build-${{ matrix.configuration }}-${{ matrix.platform }}
                  path: |
                      x64/${{ matrix.configuration }}/Engine.exe
                      x64/${{ matrix.configuration }}/Engine.pdb
                  retention-days: 7

            - name: Upload Build Logs (On Failure)
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: build-logs-${{ matrix.configuration }}-${{ matrix.platform }}
                  path: |
                      UnlearnEngine/x64/${{ matrix.configuration }}/*.log
                      *.log
                  retention-days: 7
